### ISSUE TITLE
Getting remote server returned an error and unsure how to debug

### ISSUE THREAD

**Issue by hozn** [pgspider/jdbc_fdw#5]
I'm trying to execute a simple local test using a SQLite database.  This is in a Docker container (postgres:14-bullseye).  

```
postgres=# CREATE EXTENSION jdbc_fdw;
CREATE EXTENSION 
postgres=# CREATE SERVER local_test FOREIGN DATA WRAPPER jdbc_fdw OPTIONS(
    drivername 'org.sqlite.JDBC',
    url 'jdbc:sqlite:/test.db',
    querytimeout '15',
    jarfile '/drivers/sqlite-jdbc-3.36.0.3.jar',
    maxheapsize '600'
);
CREATE SERVER
postgres=# CREATE USER MAPPING IF NOT EXISTS FOR PUBLIC SERVER local_test;
CREATE USER MAPPING
postgres=# IMPORT FOREIGN SCHEMA public LIMIT TO (foo) FROM SERVER local_test INTO public;
DEBUG:  jdbc_fdw : jdbcImportForeignSchema
ERROR:  remote server returned an error
```

How do I view the remote error in this case?  

The database is located at `/test.db` path and I have the necessary driver:
```
root@c36e76cbbe4d:/# ls -l /test.db
-rw-r--r-- 1 root root 8192 Jun 14 18:58 /test.db
root@c36e76cbbe4d:/# sqlite3 /test.db .schema
CREATE TABLE foo ( id integer primary key, name varchar);
```
```
root@c36e76cbbe4d:/# ls -l /drivers
total 45236
-rw-r--r-- 1  501 dialout  9731064 Jun 14 18:55 sqlite-jdbc-3.36.0.3.jar
```

I changed client_min_messages and log_min_messages to debug, but unable to get more details about what it means that "remote server returned an error" [especially in this case since there is no actual remote server].

**Comment by hozn** [comment]
I increased the logging to debug5 and see some additional log lines:
```
postgres=# IMPORT FOREIGN SCHEMA public LIMIT TO (foo) FROM SERVER local_test INTO public;
DEBUG:  jdbc_fdw : jdbcImportForeignSchema
DEBUG:  Added server = local_test to hashtable
DEBUG:  In jq_connect_db_params
DEBUG:  In jdbc_jvm_init
DEBUG:  Successfully created a JVM with 600 MB heapsize
DEBUG:  In jdbc_create_JDBC_connection
ERROR:  remote server returned an error
```

**Comment by hozn** [comment]
I modified the source to add more debug messages.  As I'm not a C programmer, I'm feeling a little unsure how to get the actual stacktrace here, but may take a stab at this:
```
postgres=# IMPORT FOREIGN SCHEMA public LIMIT TO (foo) FROM SERVER local_test INTO public;
DEBUG:  jdbc_fdw : jdbcImportForeignSchema
DEBUG:  Added server = local_test to hashtable
DEBUG:  In jq_connect_db_params
DEBUG:  In jdbc_jvm_init
DEBUG:  Classpath -Djava.class.path=/usr/lib/postgresql/14/lib
DEBUG:  Successfully created a JVM with 600 MB heapsize
DEBUG:  In jdbc_create_JDBC_connection
DEBUG:  Found JDBCUtils class.
DEBUG:  Found the JDBCUtils.createConnection method
DEBUG:  Found the JDBCUtils.getIdentifierQuoteString method
DEBUG:  Created argument array.
ERROR:  remote server returned an error java.lang.NullPointerException
postgres=#
```

**Comment by hozn** [comment]
Just to close the loop, I added some exception handling code from the android JNIHelp.c which got me to a stack trace.  Ultimately I realized that the options for user/password are required, even for SQLite.  **And** that I had set an option of `user` instead of `username`, which was resulting in the `NullPointerException`:
```
ERROR:  ERROR: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1301)
	at JDBCUtils.createConnection(JDBCUtils.java:80)
```
